### ISSUE TITLE
Some questions about Spatial Memory Bank

### ISSUE THREAD

**Issue by mrluin** [phiphiphi31/DMB#1]
Hello there,

Thanks for the great work!

I have some questions about the working pipeline of Spatial Memory Bank.

1. How can we get V_{s,k}, the way is the same with V_{a,k}? 
2. Does the 'online optimizer' block given in Fig. 3 is related to Eq. 6? In order to obtain the optimal filer, right? 
3. Could you give me some further hints of equation 7, especially the 2nd term equals to the 3rd term?
(sorry for unfamiliar with correlation filter :( 

Any explanations would be very appreciated, thanks in advance!

**Comment by phiphiphi31** [comment]
1. V_{s,k} is heat map which indicates the location of object. 
2. yes, 
3. please refer to some correlation filter paper, such as MOSSE, KCF, C-COT, ECO, ATOM,
